name: Deploy Dev Server
on:
  push:
    branches:
      - develop
      - master
      - qa

permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT: ${{
    contains(fromJson('["master"]'), github.ref_name) && 'prod' ||
    contains(fromJson('["qa"]'), github.ref_name) && 'qa' ||
    contains(fromJson('["develop"]'), github.ref_name) && 'dev' }}

jobs:
  set_up:
    environment: ${{ env.ENVIRONMENT }}

    runs-on: ubuntu-latest

    steps:
      - name: "run"
        env:
          BUCKET: ${{secrets.BUCKET }}
        run: |
          echo ${{ env.ENVIRONMENT }}
          echo $BUCKET | sed 's/./& /g'
