name: Deploy Dev Server
on:
  push:
    branches:
      - develop
      - master
      - qa

permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT: ${{
    contains(fromJson('["master"]'), github.ref_name) && 'prod' ||
    contains(fromJson('["qa"]'), github.ref_name) && 'qa' ||
    contains(fromJson('["develop"]'), github.ref_name) && 'dev' }}

jobs:
  set_up:
    runs-on: ubuntu-latest

    steps:
      - name: "run"
        run: echo "$ENVIRONMENT"
